HTTP/1.0 408 Request Time-out
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
<body>
<style>
	html {
	background-color: black;
	}

	img {
	display: block;
	margin: 0px auto;
	}
</style>
<img src="https://http.cat/408.jpg">
</body>
</html>
